name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email rodrigodesouzacastro@gmail.com
          git config --global user.name Rodrigo Castro
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/castrors/flutter_small_projects.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
